#!/bin/csh -f -x

#
# Install script
#
# Usage:  Install

cd `dirname $0` && source ./Configuration

if ( ! -d ${EGDATADIR} ) then
        mkdir -p ${EGDATADIR}
endif

if ( ! -d ${EGINPUTDIR} ) then
        mkdir -p ${EGINPUTDIR}
endif

if ( ! -d ${EGLOGSDIR} ) then
        mkdir -p ${EGLOGSDIR}
endif

if ( ! -d ${EGOUTPUTDIR} ) then
        mkdir -p ${EGOUTPUTDIR}
endif

if ( ! -d ${HUMANDATADIR} ) then
        mkdir -p ${HUMANDATADIR}
endif

if ( ! -d ${RATDATADIR} ) then
        mkdir -p ${RATDATADIR}
endif

if ( ! -d ${DOGDATADIR} ) then
        mkdir -p ${DOGDATADIR}
endif

if ( ! -d ${CHIMPDATADIR} ) then
        mkdir -p ${CHIMPDATADIR}
endif

if ( ! -d ${ARCHIVEDIR} ) then
        mkdir -p ${ARCHIVEDIR}
endif

if ( ! -d ${HUMANARCHIVEDIR} ) then
        mkdir -p ${HUMANARCHIVEDIR}
endif

if ( ! -d ${RATARCHIVEDIR} ) then
        mkdir -p ${RATARCHIVEDIR}
endif

if ( ! -d ${DOGARCHIVEDIR} ) then
        mkdir -p ${DOGARCHIVEDIR}
endif

if ( ! -d ${CHIMPARCHIVEDIR} ) then
        mkdir -p ${CHIMPARCHIVEDIR}
endif

foreach i (human rat dog chimpanzee)
cd $i
ln -s ../Configuration .
cd ..
end

