#!/bin/csh

#
# Install script
#
# Usage:  Install

cd `dirname $0` && source ./Configuration

if ( ! -d ${EGDATADIR} ) then
        mkdir -p ${EGDATADIR}
endif

if ( ! -d ${EGINPUTDIR} ) then
        mkdir -p ${EGINPUTDIR}
endif

if ( ! -d ${EGLOGSDIR} ) then
        mkdir -p ${EGLOGSDIR}
endif

if ( ! -d ${EGOUTPUTDIR} ) then
        mkdir -p ${EGOUTPUTDIR}
endif

if ( ! -d ${EGARCHIVEDIR} ) then
        mkdir -p ${EGARCHIVEDIR}
endif

foreach i (*.config)
source $i
if ( ! -d ${DATADIR} ) then
        mkdir -p ${DATADIR}
endif
if ( ! -d ${ARCHIVEDIR} ) then
        mkdir -p ${ARCHIVEDIR}
endif
if ( ! -d ${REPORTSDIR} ) then
        mkdir -p ${REPORTSDIR}
endif
end

foreach i (human rat dog chimpanzee cattle)
cd $i
rm -rf Configuration
ln -s ../Configuration .
cd ..
end

